### ISSUE TITLE
How do we run the repo for ASR? 

### ISSUE THREAD

**Issue by appledora** [tuanio/noisy-student-training-asr#1]

**Comment by tuanio** [comment]
You can use `training_teacher_ctc.py`, `training_student_ctc.py` for training your teacher model and student model, respectively. Just training the teacher, save the Conformer teacher checkpoint file, then running the training student script with your teacher checkpoint file. You can write custom dataset class for your case. 

By the way, there're the branch name `pending` is my work on restructure this code. It's will complete soon.
