### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by ShushantKQ** [tuanio/noisy-student-training-asr#2]
I want to know how to use the trained model. There is the link to the model but no information on how can we use the model.
Thanks

**Comment by tuanio** [comment]
The weights I've public is used by both teacher and student model.

You can change the path of these lines of code in the file `training_student_ctc.py` (134 - 136). 
```
teacher_checkpoint = torch.load(
    f"pretrained/teacher_2_hidden_libri_subsampling_swish.pt"
)
```

Or line 307 from `training_teacher_ctc.py`:

```
ckpt = torch.load('pretrained/teacher_2_hidden_libri_subsampling_swish.pt')
```

**Comment by YMCVICTOR** [comment]
This model file is not given in github, can you post the teacher_2_hidden_libri_subsampling_swish.pt file? Thanks.

**Comment by tuanio** [comment]
> 

Actually it's on kaggle, you can view on README.md
