### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by kekexu123** [tuanio/noisy-student-training-asr#4]
I'm sorry that this is the first time for me to start the training of speech recognition task. There are some problems when I download the pre-trained model, and there is no download link. Could you please provide me with the pre-trained model? Thank you very much!
![微信图片_20240227161707](https://github.com/tuanio/noisy-student-training-asr/assets/102705544/a64fbe95-0468-45b5-8c0f-8273600739a7)

**Comment by tuanio** [comment]
You can use it's through HuggingFace Transformers package: https://huggingface.co/facebook/wav2vec2-conformer-rel-pos-large.

Please refer to the code of training student and training teacher
