### ISSUE TITLE
information dataset

### ISSUE THREAD

**Issue by nghiavuduc** [tuanio/noisy-student-training-asr#5]
Hi b, cho mình hỏi Phonemizer đang được setup như nào? ( IPA en-us hay en-gb), Mình dùng Phonemizer nhưng kết quả k ra giống bạn( k biết bạn đang dùng backend với setting như nào). Data audio đang sử dụng là giọng us hay gb?

**Comment by tuanio** [comment]
Bạn có thể tham khảo chi tiết ở đây: https://www.kaggle.com/code/tuannguyenvananh/make-libritranscript
